spring:
  application:
    name: ewallet-user-service
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ewallet;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect